### ISSUE TITLE
博主有联系方式吗？想谈合作~

### ISSUE THREAD

**Issue by sssssshift** [open-mmlab/mmeval#116]

**Comment by zhouzaida** [comment]
你好，可以发邮件至 mmcv@openmmlab.com

**Comment by sssssshift** [comment]
好嘞 已经发咯



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
23/04/03
17:06:23

Zaida Zhou ***@***.***> 于2023年4月3日周一 15:27写道：
