### ISSUE TITLE
Calling for volunteers for adding new metrics!

### ISSUE THREAD

**Issue by ice-tong** [open-mmlab/mmeval#50]
Dear community,

We are excited to introduce our new evaluation library: MMEval, a unified evaluation library for multiple machine learning libraries. 

With the release of MMEval, we have some metrics from the OpenMMLab algorithm library that have not yet been added. We list the metrics below and call for community help. 

If you are interested, you can claim a metric by replying to this issue in the following format:
```
Metric No. : <The Metric No. you claim>
Status :  Apply | Submit
Links : The repo links you fork (Apply status) / The PR links you open (Submit status)
```

| No. | Metric | Algorithm library | Level of Difficulty | Assigned to | Status / PR | 
| :-: | :-: | :-: | :-: | :-: | :-: |
| 1 | [CityScapesMetric](50#CityScapesMetric) | mmdet / mmseg | ⭐️⭐️⭐️ | @Muyun99 | Apply
| 2 | [CocoPanopticMetric](50#CocoPanopticMetric) | mmdet | ⭐️⭐️⭐️ | @Even-ok | Apply
| 3 | [LVISMetric](50#LVISMetric) | mmdet | ⭐️⭐️ | @dmucby  | Apply
| 4 | [CrowdHumanMetric](50#CrowdHumanMetric) | mmdet | ⭐️⭐️ | @tianleiSHI | Apply
| 5 | [DOTAMetric](50#DOTAMetric) | mmrotate | ⭐️⭐️ | @YanxingLiu | #65 
| 6 | [RotatedCocoMetric](50#RotatedCocoMetric) | mmrotate | ⭐️⭐️ | @YanxingLiu |
| 7 | [IndoorMetric](50#IndoorMetric) | mmdet3d | ⭐️⭐️⭐️| |
| 8 | [InstanceSegMetric](50#InstanceSegMetric) | mmdet3d | ⭐️⭐️⭐️|  @Pzzzzz5142  | Apply
| 9 | [KittiMetric](50#KittiMetric) | mmdet3d | ⭐️⭐️⭐️| |
| 10 | [LyftMetric](50#LyftMetric) | mmdet3d | ⭐️⭐️⭐️| |
| 11 | [NuScenesMetric](50#NuScenesMetric) | mmdet3d | ⭐️⭐️⭐️| |
| 12 | [WaymoMetric](50#WaymoMetric) | mmdet3d | ⭐️⭐️⭐️| |
| 13 | [OneMinusNEDMetric](50#OneMinusNEDMetric) | mmocr | ⭐️⭐️| |
| 14 | [WordMetric](50#WordMetric) | mmocr | ⭐️⭐️| |
| 15 | [CharMetric](50#CharMetric) | mmocr | ⭐️⭐️| |
| 16 | [CocoWholeBodyMetric](50#CocoWholeBodyMetric) | mmpose | ⭐️⭐️| |
| 17 | [NME](50#NME) | mmpose | ⭐️⭐️| |
| 18 | [AUC](50#AUC) | mmpose | ⭐️⭐️| |
| 19 | [EPE](50#EPE) | mmpose | ⭐️⭐️| |
| 20 | [PoseTrack18Metric](50#PoseTrack18Metric) | mmpose | ⭐️⭐️| |
| 21 | [ANetMetric](50#ANetMetric) | mmaction2 | ⭐️⭐️| |
| 22 | [AccMetric](50#AccMetric) | mmaction2 | ⭐️⭐️| |
| 23 | [FlowOutliers](50#FlowOutliers) | mmflow | ⭐️⭐️| @fengsxy  |Apply
| 24 | [MOTChallengeMetrics](50#MOTChallengeMetrics) | mmtracking | ⭐️⭐️| |
| 25 | [ReIDMetrics](50#ReIDMetrics) | mmtracking | ⭐️⭐️| |
| 26 | [SOTMetric](50#SOTMetric) | mmtracking | ⭐️⭐️| |
| 27 | [TAOMetric](50#TAOMetric) | mmtracking | ⭐️⭐️| |
| 28 | [YouTubeVISMetric](50#YouTubeVISMetric) | mmtracking | ⭐️⭐️|  @qianlian-mozi | Apply
| 29 | [MultiScaleStructureSimilarity](50#MultiScaleStructureSimilarity) | mmediting | ⭐️⭐️| |
| 30 | [FrechetInceptionDistance & TransFID](50#FrechetInceptionDistance) | mmediting | ⭐️⭐️| |
| 31 | [InceptionScore & TransIS](50#InceptionScore) | mmediting | ⭐️⭐️| |
| 32 | [SAD](50#SAD) | mmediting | ⭐️⭐️| @xuan07472 | #76
| 33 | [MattingMSE](50#MattingMSE) | mmediting | ⭐️⭐️| @xuan07472 | #71
| 34 | [ConnectivityError](50#ConnectivityError) | mmediting | ⭐️⭐️| @xuan07472  | #79
| 35 | [GradientError](50#GradientError) | mmediting | ⭐️⭐️|  @xuan07472 | #78 
| 36 | [PerceptualPathLength](50#PerceptualPathLength) | mmediting | ⭐️⭐️| |
| 37 | [PrecisionAndRecall](50#PrecisionAndRecall) | mmediting | ⭐️⭐️| |
| 38 | [SlicedWassersteinDistance](50#SlicedWassersteinDistance) | mmediting | ⭐️⭐️| |
| 39 | [NIQE](50#NIQE) | mmediting | ⭐️⭐️| |
| 40 | [Equivariance](50#Equivariance) | mmediting | ⭐️⭐️| |

## NOTES:
1.  Documents of MMEval can be found at: https://mmeval.readthedocs.io/en/latest/
2. The contributing guides can be found at: https://github.com/open-mmlab/mmeval/blob/main/CONTRIBUTING.md

## Examples:
We provide some examples showing how to add Metric from the OpenMMLab algorithm library to MMEval
1. mmeval.Accuracy from mmcsl
- PR in mmeval: https://github.com/open-mmlab/mmeval/pull/6
- PR in mmcls: https://github.com/open-mmlab/mmclassification/pull/1046
2. mmeval.MeanIoU from mmseg
- PR in mmeval: https://github.com/open-mmlab/mmeval/pull/7
- PR in mmseg: https://github.com/open-mmlab/mmsegmentation/pull/2003
3. mmeval.VOCMeanAP from mmdet
- PR in mmeval: https://github.com/open-mmlab/mmeval/pull/8
- PR in mmdet: https://github.com/open-mmlab/mmdetection/pull/8897
4. mmeval.COCODetectionMetric from mmdet
- PR in mmeval: https://github.com/open-mmlab/mmeval/pull/23
- PR in mmdet: https://github.com/open-mmlab/mmdetection/pull/9079

#  Submitted Content:
1. The PR in MMEval that adds the new metric (with complete documentation and testing)
2. The PR in original algorithm library that uses the new metric  (with evaluation comparison between using MMEval and before)

<h2 id="CityScapesMetric">No1. CityScapesMetric</h3>

- Add the CityScapesMetric from mmdet / mmseg to MMEval, and use the MMEval's CityScapesMetric in mmdet / mmseg.
- Technical Tags: Python; Object detection; Semantic segmentation;
- The original CityScapesMetric in [mmdet](https://github.com/open-mmlab/mmdetection/blob/fe7dbd246cd480d6da80ca38cd39a969d2111688/mmdet/evaluation/metrics/cityscapes_metric.py#L28)
- The original CityScapesMetric in [mmseg](https://github.com/open-mmlab/mmsegmentation/blob/dev-1.x/mmseg/evaluation/metrics/citys_metric.py#L15)

<h2 id="CocoPanopticMetric">No2. CocoPanopticMetric</h3>

- Add the CocoPanopticMetric from mmdet to MMEval, and use the MMEval's CocoPanopticMetric in mmdet.
- Technical Tags: Python; Object detection; Panoptic segmentation;
- The original CocoPanopticMetric in [mmdet](https://github.com/open-mmlab/mmdetection/blob/fe7dbd246cd480d6da80ca38cd39a969d2111688/mmdet/evaluation/metrics/coco_panoptic_metric.py#L33)

<h2 id="LVISMetric">No3. LVISMetric</h3>

- Add the LVISMetric from mmdet to MMEval, and use the MMEval's LVISMetric in mmdet.
- Technical Tags: Python; Object detection;
- The original LVISMetric in [mmdet](https://github.com/open-mmlab/mmdetection/blob/fe7dbd246cd480d6da80ca38cd39a969d2111688/mmdet/evaluation/metrics/lvis_metric.py#L32)

<h2 id="CrowdHumanMetric">No4. CrowdHumanMetric</h3>

- Add the CrowdHumanMetric from mmdet to MMEval, and use the MMEval's CrowdHumanMetric in mmdet.
- Technical Tags: Python; Object detection;
- The original CrowdHumanMetric in [mmdet](https://github.com/open-mmlab/mmdetection/blob/fe7dbd246cd480d6da80ca38cd39a969d2111688/mmdet/evaluation/metrics/crowdhuman_metric.py#L24)

<h2 id="DOTAMetric">No5. DOTAMetric</h3>

- Add the DOTAMetric from mmrotate to MMEval, and use the MMEval's DOTAMetric in mmrotate.
- Technical Tags: Python; Rotated object detection;
- The original DOTAMetric in [mmrotate](https://github.com/open-mmlab/mmrotate/blob/32cc5ae5660eaa4830c86a00830c35dfe6eef724/mmrotate/evaluation/metrics/dota_metric.py#L24)

<h2 id="RotatedCocoMetric">No6. RotatedCocoMetric</h3>

- Add the RotatedCocoMetric from mmrotate to MMEval, and use the MMEval's RotatedCocoMetric in mmrotate.
- Technical Tags: Python; Rotated object detection;
- The original RotatedCocoMetric in [mmrotate](https://github.com/open-mmlab/mmrotate/blob/32cc5ae5660eaa4830c86a00830c35dfe6eef724/mmrotate/evaluation/metrics/rotated_coco_metric.py#L78)

<h2 id="IndoorMetric">No7. IndoorMetric</h3>

- Add the IndoorMetric from mmdet3d to MMEval, and use the MMEval's IndoorMetric in mmdet3d.
- Technical Tags: Python; 3D object detection;
- The original IndoorMetric in [mmdet3d](https://github.com/open-mmlab/mmdetection3d/blob/96c99f51d49461c5dcf270073229ee067249bfbc/mmdet3d/evaluation/metrics/indoor_metric.py#L16)

<h2 id="InstanceSegMetric">No8. InstanceSegMetric</h3>

- Add the InstanceSegMetric from mmdet3d to MMEval, and use the MMEval's InstanceSegMetric in mmdet3d.
- Technical Tags: Python; 3D instance segmentation;
- The original InstanceSegMetric in [mmdet3d](https://github.com/open-mmlab/mmdetection3d/blob/96c99f51d49461c5dcf270073229ee067249bfbc/mmdet3d/evaluation/metrics/instance_seg_metric.py#L12)

<h2 id="KittiMetric">No9. KittiMetric</h3>

- Add the KittiMetric from mmdet3d to MMEval, and use the MMEval's KittiMetric in mmdet3d.
- Technical Tags: Python; 3D object detection;
- The original KittiMetric in [mmdet3d](https://github.com/open-mmlab/mmdetection3d/blob/96c99f51d49461c5dcf270073229ee067249bfbc/mmdet3d/evaluation/metrics/kitti_metric.py#L20)

<h2 id="LyftMetric">No10. LyftMetric</h3>

- Add the LyftMetric from mmdet3d to MMEval, and use the MMEval's LyftMetric in mmdet3d.
- Technical Tags: Python; 3D object detection;
- The original LyftMetric in [mmdet3d](https://github.com/open-mmlab/mmdetection3d/blob/96c99f51d49461c5dcf270073229ee067249bfbc/mmdet3d/evaluation/metrics/lyft_metric.py#L23)

<h2 id="NuScenesMetric">No11. NuScenesMetric</h3>

- Add the NuScenesMetric from mmdet3d to MMEval, and use the MMEval's NuScenesMetric in mmdet3d.
- Technical Tags: Python; 3D object detection;
- The original NuScenesMetric in [mmdet3d](https://github.com/open-mmlab/mmdetection3d/blob/96c99f51d49461c5dcf270073229ee067249bfbc/mmdet3d/evaluation/metrics/nuscenes_metric.py#L25)

<h2 id="WaymoMetric">No12. WaymoMetric</h3>

- Add the WaymoMetric from mmdet3d to MMEval, and use the MMEval's WaymoMetric in mmdet3d.
- Technical Tags: Python; 3D object detection;
- The original WaymoMetric in [mmdet3d](https://github.com/open-mmlab/mmdetection3d/blob/96c99f51d49461c5dcf270073229ee067249bfbc/mmdet3d/evaluation/metrics/waymo_metric.py#L21)

<h2 id="OneMinusNEDMetric">No13. OneMinusNEDMetric</h3>

- Add the OneMinusNEDMetric from mmocr to MMEval, and use the MMEval's OneMinusNEDMetric in mmocr.
- Technical Tags: Python; OCR;
- The original OneMinusNEDMetric in [mmocr](https://github.com/open-mmlab/mmocr/blob/abf5a8972c2e4d9855164794c5ce0687d9a4dea0/mmocr/evaluation/metrics/recog_metric.py#L228)

<h2 id="WordMetric">No14. WordMetric</h3>

- Add the WordMetric from mmocr to MMEval, and use the MMEval's WordMetric in mmocr.
- Technical Tags: Python; OCR;
- The original WordMetric in [mmocr](https://github.com/open-mmlab/mmocr/blob/abf5a8972c2e4d9855164794c5ce0687d9a4dea0/mmocr/evaluation/metrics/recog_metric.py#L14)

<h2 id="CharMetric">No15. CharMetric</h3>

- Add the CharMetric from mmocr to MMEval, and use the MMEval's CharMetric in mmocr.
- Technical Tags: Python; OCR;
- The original CharMetric in [mmocr](https://github.com/open-mmlab/mmocr/blob/abf5a8972c2e4d9855164794c5ce0687d9a4dea0/mmocr/evaluation/metrics/recog_metric.py#L127)

<h2 id="CocoWholeBodyMetric">No16. CocoWholeBodyMetric</h3>

- Add the CocoWholeBodyMetric from mmpose to MMEval, and use the MMEval's CocoWholeBodyMetric in mmpose.
- Technical Tags: Python; Pose estimation;
- The original CocoWholeBodyMetric in [mmpose](https://github.com/open-mmlab/mmpose/blob/33d4a3ed0e7982a00f40d97a98e25366e008371f/mmpose/evaluation/metrics/coco_wholebody_metric.py#L13)

<h2 id="NME">No17. NME</h3>

- Add the NME from mmpose to MMEval, and use the MMEval's NME in mmpose.
- Technical Tags: Python; Pose estimation;
- The original NME in [mmpose](https://github.com/open-mmlab/mmpose/blob/33d4a3ed0e7982a00f40d97a98e25366e008371f/mmpose/evaluation/metrics/keypoint_2d_metrics.py#L713)

<h2 id="AUC">No18. AUC</h3>

- Add the AUC from mmpose to MMEval, and use the MMEval's AUC in mmpose.
- Technical Tags: Python; Pose estimation;
- The original AUC in [mmpose](https://github.com/open-mmlab/mmpose/blob/33d4a3ed0e7982a00f40d97a98e25366e008371f/mmpose/evaluation/metrics/keypoint_2d_metrics.py#L536)

<h2 id="EPE">No19. EPE</h3>

- Add the EPE from mmpose to MMEval, and use the MMEval's EPE in mmpose.
- Technical Tags: Python; Pose estimation;
- The original EPE in [mmpose](https://github.com/open-mmlab/mmpose/blob/33d4a3ed0e7982a00f40d97a98e25366e008371f/mmpose/evaluation/metrics/keypoint_2d_metrics.py#L632)

<h2 id="PoseTrack18Metric">No20. PoseTrack18Metric</h3>

- Add the PoseTrack18Metric from mmpose to MMEval, and use the MMEval's PoseTrack18Metric in mmpose.
- Technical Tags: Python; Pose estimation;
- The original PoseTrack18Metric in [mmpose](https://github.com/open-mmlab/mmpose/blob/33d4a3ed0e7982a00f40d97a98e25366e008371f/mmpose/evaluation/metrics/posetrack18_metric.py#L22)

<h2 id="ANetMetric">No21. ANetMetric</h3>

- Add the ANetMetric from mmaction2 to MMEval, and use the MMEval's ANetMetric in mmaction2.
- Technical Tags: Python; Video understanding;
- The original ANetMetric in [mmaction2](https://github.com/open-mmlab/mmaction2/blob/350b117bd1527558cfd6e7eba07a77dbcbbd3cda/mmaction/evaluation/metrics/anet_metric.py#L18)

<h2 id="AccMetric">No22. AccMetric</h3>

- Add the AccMetric from mmaction2 to MMEval, and use the MMEval's AccMetric in mmaction2.
- Technical Tags: Python; Video understanding;
- The original AccMetric in [mmaction2](https://github.com/open-mmlab/mmaction2/blob/350b117bd1527558cfd6e7eba07a77dbcbbd3cda/mmaction/evaluation/metrics/acc_metric.py#L15)

<h2 id="FlowOutliers">No23. FlowOutliers </h3>

- Add the FlowOutliers from mmflow to MMEval, and use the MMEval's FlowOutliers in mmflow.
- Technical Tags: Python; Optical flow;
- The original FlowOutliers in [mmflow](https://github.com/open-mmlab/mmflow/blob/712ffdbf3dd0ac30cc5df7eb43e50ec8735ea858/mmflow/evaluation/metrics/optical_flow_outliers.py#L12)

<h2 id="MOTChallengeMetrics">No24. MOTChallengeMetrics </h3>

- Add the MOTChallengeMetrics from mmtracking to MMEval, and use the MMEval's MOTChallengeMetrics in mmtracking.
- Technical Tags: Python; Multiple object tracking;
- The original MOTChallengeMetrics in [mmtracking](https://github.com/open-mmlab/mmtracking/blob/c86e1b9f3127c5a1f844854537eddaf37e112591/mmtrack/evaluation/metrics/mot_challenge_metrics.py#L38)

<h2 id="ReIDMetrics">No25. ReIDMetrics </h3>

- Add the ReIDMetrics from mmtracking to MMEval, and use the MMEval's ReIDMetrics in mmtracking.
- Technical Tags: Python; Re-identification;
- The original ReIDMetrics in [mmtracking](https://github.com/open-mmlab/mmtracking/blob/c86e1b9f3127c5a1f844854537eddaf37e112591/mmtrack/evaluation/metrics/reid_metrics.py#L12)

<h2 id="SOTMetric">No26. SOTMetric </h3>

- Add the SOTMetric from mmtracking to MMEval, and use the MMEval's SOTMetric in mmtracking.
- Technical Tags: Python; Single object tracking;
- The original SOTMetric in [mmtracking](https://github.com/open-mmlab/mmtracking/blob/c86e1b9f3127c5a1f844854537eddaf37e112591/mmtrack/evaluation/metrics/sot_metrics.py#L24)

<h2 id="TAOMetric">No27. TAOMetric </h3>

- Add the TAOMetric from mmtracking to MMEval, and use the MMEval's TAOMetric in mmtracking.
- Technical Tags: Python; Object tracking;
- The original TAOMetric in [mmtracking](https://github.com/open-mmlab/mmtracking/blob/c86e1b9f3127c5a1f844854537eddaf37e112591/mmtrack/evaluation/metrics/tao_metrics.py#L28)

<h2 id="YouTubeVISMetric">No28. YouTubeVISMetric </h3>

- Add the YouTubeVISMetric from mmtracking to MMEval, and use the MMEval's YouTubeVISMetric in mmtracking.
- Technical Tags: Python; Video instance segmentation;
- The original YouTubeVISMetric in [mmtracking](https://github.com/open-mmlab/mmtracking/blob/c86e1b9f3127c5a1f844854537eddaf37e112591/mmtrack/evaluation/metrics/youtube_vis_metrics.py#L22)

<h2 id="MultiScaleStructureSimilarity">No29. MultiScaleStructureSimilarity </h3>

- Add the MultiScaleStructureSimilarity from mmediting to MMEval, and use the MMEval's MultiScaleStructureSimilarity in mmediting.
- Technical Tags: Python; GAN;
- The original MultiScaleStructureSimilarity in [mmediting](https://github.com/open-mmlab/mmediting/blob/b70695d6d7217408d16ad538da1a2c716d2ff65f/mmedit/evaluation/metrics/ms_ssim.py#L229)

<h2 id="FrechetInceptionDistance">No30. FrechetInceptionDistance & TransFID </h3>

- Add the FrechetInceptionDistance and TransFID from mmediting to MMEval, and use the MMEval's FrechetInceptionDistance and TransFID in mmediting.
- Technical Tags: Python; GAN;
- The original FrechetInceptionDistance in [mmediting](https://github.com/open-mmlab/mmediting/blob/b70695d6d7217408d16ad538da1a2c716d2ff65f/mmedit/evaluation/metrics/fid.py#L21)
- The original TransFID in [mmediting](https://github.com/open-mmlab/mmediting/blob/b70695d6d7217408d16ad538da1a2c716d2ff65f/mmedit/evaluation/metrics/fid.py#L223)

<h2 id="InceptionScore">No31. InceptionScore & TransIS </h3>

- Add the InceptionScore and TransIS from mmediting to MMEval, and use the MMEval's  InceptionScore and TransIS in mmediting.
- Technical Tags: Python; GAN;
- The original InceptionScore in [mmediting](https://github.com/open-mmlab/mmediting/blob/b70695d6d7217408d16ad538da1a2c716d2ff65f/mmedit/evaluation/metrics/inception_score.py#L22)
- The original TransIS in [mmediting](https://github.com/open-mmlab/mmediting/blob/b70695d6d7217408d16ad538da1a2c716d2ff65f/mmedit/evaluation/metrics/inception_score.py#L254)

<h2 id="SAD">No32. SAD </h3>

- Add the SAD from mmediting to MMEval, and use the MMEval's SAD in mmediting.
- Technical Tags: Python; GAN;
- The original SAD in [mmediting](https://github.com/open-mmlab/mmediting/blob/b70695d6d7217408d16ad538da1a2c716d2ff65f/mmedit/evaluation/metrics/sad.py#L12)

<h2 id="MattingMSE">No33. MattingMSE </h3>

- Add the MattingMSE from mmediting to MMEval, and use the MMEval's MattingMSE in mmediting.
- Technical Tags: Python; Matting;
- The original MattingMSE in [mmediting](https://github.com/open-mmlab/mmediting/blob/b70695d6d7217408d16ad538da1a2c716d2ff65f/mmedit/evaluation/metrics/matting_mse.py#L11)

<h2 id="ConnectivityError">No34. ConnectivityError </h3>

- Add the ConnectivityError from mmediting to MMEval, and use the MMEval's ConnectivityError in mmediting.
- Technical Tags: Python; Matting;
- The original ConnectivityError in [mmediting](https://github.com/open-mmlab/mmediting/blob/b70695d6d7217408d16ad538da1a2c716d2ff65f/mmedit/evaluation/metrics/connectivity_error.py#L15)

<h2 id="GradientError">No35. GradientError </h3>

- Add the GradientError from mmediting to MMEval, and use the MMEval's GradientError in mmediting.
- Technical Tags: Python; Matting;
- The original GradientError in [mmediting](https://github.com/open-mmlab/mmediting/blob/b70695d6d7217408d16ad538da1a2c716d2ff65f/mmedit/evaluation/metrics/gradient_error.py#L14)

<h2 id="PerceptualPathLength">No36. PerceptualPathLength </h3>

- Add the PerceptualPathLength from mmediting to MMEval, and use the MMEval's PerceptualPathLength in mmediting.
- Technical Tags: Python; GAN;
- The original PerceptualPathLength in [mmediting](https://github.com/open-mmlab/mmediting/blob/b70695d6d7217408d16ad538da1a2c716d2ff65f/mmedit/evaluation/metrics/ppl.py#L52)

<h2 id="PrecisionAndRecall">No37. PrecisionAndRecall </h3>

- Add the PrecisionAndRecall from mmediting to MMEval, and use the MMEval's PrecisionAndRecall in mmediting.
- Technical Tags: Python; GAN;
- The original PrecisionAndRecall in [mmediting](https://github.com/open-mmlab/mmediting/blob/b70695d6d7217408d16ad538da1a2c716d2ff65f/mmedit/evaluation/metrics/precision_and_recall.py#L49)

<h2 id="SlicedWassersteinDistance">No38. SlicedWassersteinDistance </h3>

- Add the SlicedWassersteinDistance from mmediting to MMEval, and use the MMEval's SlicedWassersteinDistance in mmediting.
- Technical Tags: Python; GAN;
- The original SlicedWassersteinDistance in [mmediting](https://github.com/open-mmlab/mmediting/blob/b70695d6d7217408d16ad538da1a2c716d2ff65f/mmedit/evaluation/metrics/swd.py#L187)

<h2 id="NIQE">No39. NIQE </h3>

- Add the NIQE from mmediting to MMEval, and use the MMEval's NIQE in mmediting.
- Technical Tags: Python; GAN;
- The original NIQE in [mmediting](https://github.com/open-mmlab/mmediting/blob/b70695d6d7217408d16ad538da1a2c716d2ff65f/mmedit/evaluation/metrics/niqe.py#L19)

<h2 id="Equivariance">No40. Equivariance </h3>

- Add the Equivariance from mmediting to MMEval, and use the MMEval's Equivariance in mmediting.
- Technical Tags: Python; GAN;
- The original Equivariance in [mmediting](https://github.com/open-mmlab/mmediting/blob/b70695d6d7217408d16ad538da1a2c716d2ff65f/mmedit/evaluation/metrics/equivariance.py#L18)

**Comment by YanxingLiu** [comment]
Metric No.5 https://github.com/open-mmlab/mmeval/issues/50#DOTAMetric
Status : Apply
Links : https://github.com/YanxingLiu/mmeval.git

**Comment by dmucby** [comment]
Metric No.3 [LVISMetric](https://github.com/open-mmlab/mmeval/issues/50#LVISMetric)
Status : Apply
Links : https://github.com/dmucby/mmeval

**Comment by xuan07472** [comment]
Metric No33. MattingMSE
Status :  Apply 
Links : https://github.com/xuan07472/mmeval

**Comment by tianleiSHI** [comment]
Metric No.4 [CrowdHumanMetric](https://github.com/open-mmlab/mmeval/issues/50#CrowdHumanMetric)
Status: Apply
Links: https://github.com/tianleiSHI/mmeval

**Comment by Pzzzzz5142** [comment]
Metric No.8 [InstanceSegMetric](https://github.com/open-mmlab/mmeval/issues/50#InstanceSegMetric)
Status: Apply
Links: https://github.com/Pzzzzz5142/mmeval

**Comment by xuan07472** [comment]
Metric No.32 [SAD](https://github.com/open-mmlab/mmeval/issues/50#SAD)
Status :  Apply 
Links : https://github.com/xuan07472/mmeval

**Comment by xuan07472** [comment]
Metric No.33 [MattingMSE](https://github.com/open-mmlab/mmeval/issues/50#MattingMSE)
Status :  Submit
Links : https://github.com/open-mmlab/mmeval/pull/71#issue-1514344586

**Comment by xuan07472** [comment]
Metric No.32 [SAD](https://github.com/open-mmlab/mmeval/issues/50#SAD)
Status :  Submit
Links : https://github.com/open-mmlab/mmeval/pull/76

**Comment by YanxingLiu** [comment]
Metric No.5 https://github.com/open-mmlab/mmeval/issues/50#DOTAMetric
Status : Submit
Links : https://github.com/YanxingLiu/mmeval.git

**Comment by qianlian-mozi** [comment]
Metric No.28 : <YouTubeVISMetric>
Status :  Apply
Links : https://github.com/qianlian-mozi/mmeval

**Comment by xuan07472** [comment]
Metric No.35 [GradientError](https://github.com/open-mmlab/mmeval/issues/50#SAD)
Status :  Apply 
Links : https://github.com/xuan07472/mmeval

**Comment by xuan07472** [comment]
Metric No.35 [GradientError](https://github.com/open-mmlab/mmeval/issues/50#GradientError)
Status :  Submit
Links : https://github.com/open-mmlab/mmeval/pull/78

**Comment by xuan07472** [comment]
Metric No.35 [ConnectivityError](https://github.com/open-mmlab/mmeval/issues/50#ConnectivityError)
Status :  Apply 
Links : https://github.com/xuan07472/mmeval

**Comment by xuan07472** [comment]
Metric No.34 [ConnectivityError](https://github.com/open-mmlab/mmeval/issues/50#ConnectivityError)
Status :  Submit
Links : https://github.com/open-mmlab/mmediting/pull/1600

**Comment by YanxingLiu** [comment]
Metric No.6 [RotatedCocoMetric](https://github.com/open-mmlab/mmeval/issues/50#RotatedCocoMetric)
Satus: Apply
Links: https://github.com/YanxingLiu/mmeval.git
