### ISSUE TITLE
Some question about PSNR metric

### ISSUE THREAD

**Issue by BIGWangYuDong** [open-mmlab/mmeval#51]
Codes:
https://github.com/open-mmlab/mmeval/blob/e2f6dbf160d41adfa185caed211f2ac50747f3ba/mmeval/metrics/psnr.py#L71-L100

Seems `channel_order` will not be used if channel_order is not None

## way to fix:

maybe change self.channel_order -> channel_order is OK?

**Comment by LeoXing1996** [comment]
@BIGWangYuDong, thanks for your reporting! I will check all metrics related to low-level vision and fix this problem as soon as possible!

**Comment by zhouzaida** [comment]
closed by #89
